### ISSUE TITLE
Error when trying to load YTPMVE on VEGAS PRO 16

### ISSUE THREAD

**Issue by RedDragonTix** [Cantersoft/YTPMVE#19] opened 2023-05-20 18:19 UTC
An error occured during execution of the script C:\Program Files\VEGAS\VEGAS Pro 16.0\Script Menu\YTPMVE\YTPMVE.exe

The module was expected to contain an assembly manifest.

System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files\VEGAS\VEGAS Pro 16.0\Script Menu\YTPMVE\YTPMVE.exe' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///C:\Program Files\VEGAS\VEGAS Pro 16.0\Script Menu\YTPMVE\YTPMVE.exe'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at ScriptPortal.Vegas.ScriptHost.PrecompiledScriptManager.Run()
   at ScriptPortal.Vegas.ScriptHost.RunScript(Boolean fCompileOnly)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Cantersoft** [comment] 2023-08-16 21:29
Did you download from the *.zip file on [the releases page](https://github.com/Cantersoft/YTPMVE/releases)? Any other way of downloading will not compile the executable file.

**Comment by RedDragonTix** [comment] 2023-11-10 08:24
> Did you download from the *.zip file on [the releases page](https://github.com/Cantersoft/YTPMVE/releases)? Any other way of downloading will not compile the executable file.

I did

**Comment by Cantersoft** [comment] 2023-11-18 20:08
To me, this is indicating either that you executed `YTPMVE.exe` instead of `Run Script - Vegas 13+.cs` from the script menu, or that for some other reason the executable did not download correctly.

**Comment by Cantersoft** [comment] 2023-11-21 16:48
With the latest update, I've changed the way the files are stored so that it's impossible to run the wrong file. Check it out when you've got time.

**Comment by Cantersoft** [comment] 2023-12-29 17:31
Closing this issue since the cause has likely been fixed. Feel free to open another issue if you still need help.

**Closed as completed by Cantersoft** 2023-12-29 17:31 UTC
